---
resource_types:
- name: bosh-deployment
  type: registry-image
  source: {repository: cloudfoundry/bosh-deployment-resource}

- name: pull-request
  type: registry-image
  source: {repository: teliaoss/github-pr-resource}


resources:
- name: concourse-pr
  type: pull-request
  source:
    repository: concourse/concourse
    access_token: ((pull_requests_access_token))

- name: baggageclaim-pr
  type: pull-request
  source:
    repository: concourse/baggageclaim
    access_token: ((pull_requests_access_token))

- name: dev-image
  type: registry-image
  source: {repository: concourse/dev}

- name: postgres-image
  type: registry-image
  source: {repository: postgres}


jobs:
- name: unit
  public: true
  serial: true
  on_failure:
    put: concourse-pr
    params: {path: concourse-pr, status: failure, context: unit}
  on_success:
    put: concourse-pr
    params: {path: concourse-pr, status: success, context: unit}
  plan:
  - get: concourse-pr
    trigger: true
    version: every
  - put: concourse-pr
    params: {path: concourse-pr, status: pending, context: unit}
  - task: yarn-test
    file: concourse-pr/ci/tasks/yarn-test.yml
    input_mapping: {concourse: concourse-pr}
  - task: unit
    timeout: 1h
    file: concourse-pr/ci/tasks/unit.yml
    input_mapping: {concourse: built-concourse}
    tags: [pr]

- name: testflight
  public: true
  serial: true
  on_failure:
    put: concourse-pr
    params: {path: concourse-pr, status: failure, context: testflight}
  on_success:
    put: concourse-pr
    params: {path: concourse-pr, status: success, context: testflight}
  plan:
  - aggregate:
    - get: concourse-pr
      trigger: true
      version: every
    - get: dev-image
      params: {format: oci}
    - get: postgres-image
      params: {format: oci}
  - put: concourse-pr
    params: {path: concourse-pr, status: pending, context: testflight}
  - task: yarn-build
    file: concourse-pr/ci/tasks/yarn-build.yml
    input_mapping: {concourse: concourse-pr}
  - task: testflight
    timeout: 1h
    privileged: true
    file: concourse-pr/ci/tasks/docker-compose-testflight.yml
    input_mapping: {concourse: built-concourse}
    tags: [pr]

- name: watsjs
  public: true
  serial: true
  on_failure:
    put: concourse-pr
    params: {path: concourse-pr, status: failure, context: watsjs}
  on_success:
    put: concourse-pr
    params: {path: concourse-pr, status: success, context: watsjs}
  plan:
  - aggregate:
    - get: concourse-pr
      trigger: true
      version: every
    - get: dev-image
      params: {format: oci}
    - get: postgres-image
      params: {format: oci}
  - put: concourse-pr
    params: {path: concourse-pr, status: pending, context: watsjs}
  - task: yarn-build
    file: concourse-pr/ci/tasks/yarn-build.yml
    input_mapping: {concourse: concourse-pr}
  - task: watsjs
    timeout: 1h
    privileged: true
    file: concourse-pr/ci/tasks/docker-compose-watsjs.yml
    input_mapping: {concourse: built-concourse}
    tags: [pr]

- name: baggageclaim
  public: true
  on_failure:
    put: baggageclaim-pr
    params: {path: baggageclaim-pr, status: failure, context: baggageclaim}
  on_success:
    put: baggageclaim-pr
    params: {path: baggageclaim-pr, status: success, context: baggageclaim}
  plan:
  - get: baggageclaim-pr
    trigger: true
    version: every
  - put: baggageclaim-pr
    params: {path: baggageclaim-pr, status: pending, context: baggageclaim}
  - task: unit-linux
    privileged: true
    timeout: 1h
    file: baggageclaim-pr/ci/unit-linux.yml
    input_mapping: {baggageclaim: baggageclaim-pr}
    tags: [pr]
