version: '3'

services:
  db:
    image: postgres
    ports: ["6543:5432"]
    environment:
    - POSTGRES_DB=concourse
    - POSTGRES_USER=dev
    - POSTGRES_PASSWORD=

  web:
    build:
      context: .
      dockerfile: ${DOCKERFILE}
    volumes:
    - .:/src
    command: web
    depends_on: [db]
    ports: ["8080:8080"]
    environment:
    - CONCOURSE_POSTGRES_HOST=db
    - CONCOURSE_POSTGRES_USER=dev
    - CONCOURSE_POSTGRES_PASSWORD=dev
    - CONCOURSE_POSTGRES_DATABASE=concourse
    - CONCOURSE_EXTERNAL_URL=http://localhost:8080
    - CONCOURSE_ADD_LOCAL_USER=test:test,guest:guest
    - CONCOURSE_MAIN_TEAM_LOCAL_USER=test
    - CONCOURSE_TSA_HEARTBEAT_INTERVAL=5s
    - CONCOURSE_LOG_LEVEL=debug

  worker:
    build:
      context: .
      dockerfile: ${DOCKERFILE}
    command: worker
    privileged: true
    depends_on: [web]
    ports: ["7777:7777", "7788:7788"]
    environment:
    - CONCOURSE_TSA_HOST=web:2222
    - CONCOURSE_EPHEMERAL=true

      # avoid using loopbacks
    - CONCOURSE_BAGGAGECLAIM_DRIVER=overlay

      # so that CI can configure a different network range that doesn't overlap
      # with the outer Garden
    - CONCOURSE_GARDEN_NETWORK_POOL
