---
resources:
- name: controlled-timer
  type: time
  source: {interval: 1s}
  check_every: 24h # disable continuous checking

jobs:
- name: use-doomed-worker
  plan:
  - get: controlled-timer
    tags: [doomed]

- name: use-safe-worker
  plan:
  - get: controlled-timer
