---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: concourse/dev
    tag: latest

inputs:
- name: helm-chart
- name: concourse

run:
  path: concourse/ci/tasks/scripts/check-helm-chart-parameters
