---
platform: windows

inputs:
- name: concourse
- name: version
  optional: true
- name: final-version
  optional: true
- name: fly-linux
  optional: true
- name: fly-windows
  optional: true
- name: fly-darwin
  optional: true

outputs:
- name: concourse-windows

caches:
- path: gopath

run:
  path: powershell.exe
  args: [concourse/ci/tasks/scripts/concourse-build-windows.ps1]
