---
platform: linux

image_resource:
  type: registry-image
  source: {repository: concourse/unit}

inputs:
- name: concourse
- name: dev-image
  optional: true
- name: postgres-image
  optional: true

caches:
- path: gopath
- path: concourse/web/wats/node_modules

params:
  DOCKERFILE: Dockerfile

run:
  path: concourse/ci/tasks/scripts/with-docker-compose
  args: [concourse/ci/tasks/scripts/watsjs]
