---
platform: windows

inputs:
- name: concourse
- name: final-version
  optional: true

outputs:
- name: fly-windows

caches:
- path: gopath

run:
  path: powershell
  args: [concourse/ci/tasks/scripts/fly-build.ps1]
