---
platform: linux

image_resource:
  type: registry-image
  source: {repository: golang}

inputs:
- name: concourse
- name: final-version
  optional: true

outputs:
- name: fly-linux

caches:
- path: gopath

run:
  path: concourse/ci/tasks/scripts/fly-build
