---
platform: windows

inputs:
- name: concourse
- name: final-version
  optional: true

outputs:
- name: fly-windows

# won't work until https://github.com/concourse/concourse/issues/2506 is fixed
# caches:
# - path: gopath

run:
  path: powershell
  args: [concourse/ci/tasks/scripts/fly-build.ps1]
